### ISSUE TITLE
Crash if there are nothing to onboarding

### ISSUE THREAD

**Issue by spdkimo** [Samsung/ioter#69]
Crash occurs if there are no device requiring to Auto-onboarding

Traceback (most recent call last):
  File "/home/iot/ioter/src/main.py", line 196, in start_auto_onboarding
    self.auto_onboarding = self.create_dialog(self.auto_onboarding, auto_onboardingWindow)
  File "/home/iot/ioter/src/main.py", line 163, in create_dialog
    obj = cls_name(self)
  File "/home/iot/ioter/src/auto_onboarding/auto_onboardingmain.py", line 140, in __init__
    self.init_ui_setting()
  File "/home/iot/ioter/src/auto_onboarding/auto_onboardingmain.py", line 166, in init_ui_setting
    self.objs[0].combo_device_type.width())
IndexError: list index out of range

**Comment by spdkimo** [comment]
I can't reproduce the issue with latest version
